version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - app-network

  streamlit_app:
    build: .
    container_name: streamlit_app
    depends_on:
      - sqlserver
    environment:
      SQL_SERVER_HOST: sqlserver
      SQL_SERVER_PORT: 1433
      SQL_SERVER_USER: sa
      SQL_SERVER_PASSWORD: YourStrong!Passw0rd
    ports:
      - "8501:8501"
    networks:
      - app-network

networks:
  app-network:
